seller:
  address:  0x?????
  privatekey: f305a2832172cc0c28e0e8547c690ba9e80973810c7608bbe3f295???????

buyer:
  address: ?????
  privatekey: ?????

contract:
  address: 0x?????

node:
  url: wss://sepolia.infura.io/ws/v3/??????